title: Urbanfootprint

email: sharni@sharniallen.com
description: >- # this means to ignore newlines until "baseurl:"
  Simple explaination of the product or service.
baseurl: "/Urbanfootprint" # the subpath of your site, e.g. /blog
url: "https://sharniallen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Urbanfootprint
github_username:  SharniAllen

browserTitle: Urban Test

stage: prototype

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

remote_theme: tjharrop/NSW-jekyll-theme
